name: runner-github

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12.14.0'

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build
